import { TemplateResult } from '../node_modules/lit-html/lit-html.js';
export interface HTMLClass extends HTMLElement {
    new (): HTMLClass;
}
export interface properties {
    [propName: string]: propConfig;
}
export interface propConfig {
    type: typeof String | typeof Number | typeof Boolean | typeof Array | typeof Object;
    reflectToAttribute?: boolean;
    value?: any;
    observer?: string;
}
export interface data {
    [propName: string]: any;
}
export interface methodsToCall {
    [propName: string]: (value: any) => void;
}
export interface HTMLCollectionByID {
    [id: string]: HTMLElement | Element;
}
export declare const LitElement: (superclass: HTMLClass) => {
    new (): {
        new (): HTMLClass;
        __data: data;
        _methodsToCall: methodsToCall;
        _wait: boolean;
        afterFirstRender?: (() => void) | undefined;
        shadowRoot: ShadowRoot;
        _propAttr: Map<string, string>;
        _attrProp: Map<string, string>;
        connectedCallback(): void;
        _makeGetterSetter(prop: string, info: propConfig): void;
        _propertiesChanged(prop: string, val: any): void;
        attributeChangedCallback(attr: string, old: any, val: any): void;
        render(): TemplateResult;
        readonly $: HTMLCollectionByID;
        accessKey: string;
        readonly children: HTMLCollection;
        contentEditable: string;
        readonly dataset: DOMStringMap;
        dir: string;
        draggable: boolean;
        hidden: boolean;
        hideFocus: boolean;
        innerText: string;
        readonly isContentEditable: boolean;
        lang: string;
        readonly offsetHeight: number;
        readonly offsetLeft: number;
        readonly offsetParent: Element;
        readonly offsetTop: number;
        readonly offsetWidth: number;
        onabort: (this: HTMLElement, ev: UIEvent) => any;
        onactivate: (this: HTMLElement, ev: UIEvent) => any;
        onbeforeactivate: (this: HTMLElement, ev: UIEvent) => any;
        onbeforecopy: (this: HTMLElement, ev: ClipboardEvent) => any;
        onbeforecut: (this: HTMLElement, ev: ClipboardEvent) => any;
        onbeforedeactivate: (this: HTMLElement, ev: UIEvent) => any;
        onbeforepaste: (this: HTMLElement, ev: ClipboardEvent) => any;
        onblur: (this: HTMLElement, ev: FocusEvent) => any;
        oncanplay: (this: HTMLElement, ev: Event) => any;
        oncanplaythrough: (this: HTMLElement, ev: Event) => any;
        onchange: (this: HTMLElement, ev: Event) => any;
        onclick: (this: HTMLElement, ev: MouseEvent) => any;
        oncontextmenu: (this: HTMLElement, ev: PointerEvent) => any;
        oncopy: (this: HTMLElement, ev: ClipboardEvent) => any;
        oncuechange: (this: HTMLElement, ev: Event) => any;
        oncut: (this: HTMLElement, ev: ClipboardEvent) => any;
        ondblclick: (this: HTMLElement, ev: MouseEvent) => any;
        ondeactivate: (this: HTMLElement, ev: UIEvent) => any;
        ondrag: (this: HTMLElement, ev: DragEvent) => any;
        ondragend: (this: HTMLElement, ev: DragEvent) => any;
        ondragenter: (this: HTMLElement, ev: DragEvent) => any;
        ondragleave: (this: HTMLElement, ev: DragEvent) => any;
        ondragover: (this: HTMLElement, ev: DragEvent) => any;
        ondragstart: (this: HTMLElement, ev: DragEvent) => any;
        ondrop: (this: HTMLElement, ev: DragEvent) => any;
        ondurationchange: (this: HTMLElement, ev: Event) => any;
        onemptied: (this: HTMLElement, ev: Event) => any;
        onended: (this: HTMLElement, ev: MediaStreamErrorEvent) => any;
        onerror: (this: HTMLElement, ev: ErrorEvent) => any;
        onfocus: (this: HTMLElement, ev: FocusEvent) => any;
        oninput: (this: HTMLElement, ev: Event) => any;
        oninvalid: (this: HTMLElement, ev: Event) => any;
        onkeydown: (this: HTMLElement, ev: KeyboardEvent) => any;
        onkeypress: (this: HTMLElement, ev: KeyboardEvent) => any;
        onkeyup: (this: HTMLElement, ev: KeyboardEvent) => any;
        onload: (this: HTMLElement, ev: Event) => any;
        onloadeddata: (this: HTMLElement, ev: Event) => any;
        onloadedmetadata: (this: HTMLElement, ev: Event) => any;
        onloadstart: (this: HTMLElement, ev: Event) => any;
        onmousedown: (this: HTMLElement, ev: MouseEvent) => any;
        onmouseenter: (this: HTMLElement, ev: MouseEvent) => any;
        onmouseleave: (this: HTMLElement, ev: MouseEvent) => any;
        onmousemove: (this: HTMLElement, ev: MouseEvent) => any;
        onmouseout: (this: HTMLElement, ev: MouseEvent) => any;
        onmouseover: (this: HTMLElement, ev: MouseEvent) => any;
        onmouseup: (this: HTMLElement, ev: MouseEvent) => any;
        onmousewheel: (this: HTMLElement, ev: WheelEvent) => any;
        onmscontentzoom: (this: HTMLElement, ev: UIEvent) => any;
        onmsmanipulationstatechanged: (this: HTMLElement, ev: MSManipulationEvent) => any;
        onpaste: (this: HTMLElement, ev: ClipboardEvent) => any;
        onpause: (this: HTMLElement, ev: Event) => any;
        onplay: (this: HTMLElement, ev: Event) => any;
        onplaying: (this: HTMLElement, ev: Event) => any;
        onprogress: (this: HTMLElement, ev: ProgressEvent) => any;
        onratechange: (this: HTMLElement, ev: Event) => any;
        onreset: (this: HTMLElement, ev: Event) => any;
        onscroll: (this: HTMLElement, ev: UIEvent) => any;
        onseeked: (this: HTMLElement, ev: Event) => any;
        onseeking: (this: HTMLElement, ev: Event) => any;
        onselect: (this: HTMLElement, ev: UIEvent) => any;
        onselectstart: (this: HTMLElement, ev: Event) => any;
        onstalled: (this: HTMLElement, ev: Event) => any;
        onsubmit: (this: HTMLElement, ev: Event) => any;
        onsuspend: (this: HTMLElement, ev: Event) => any;
        ontimeupdate: (this: HTMLElement, ev: Event) => any;
        onvolumechange: (this: HTMLElement, ev: Event) => any;
        onwaiting: (this: HTMLElement, ev: Event) => any;
        outerText: string;
        spellcheck: boolean;
        readonly style: CSSStyleDeclaration;
        tabIndex: number;
        title: string;
        blur(): void;
        click(): void;
        dragDrop(): boolean;
        focus(): void;
        msGetInputContext(): MSInputMethodContext;
        addEventListener<K extends "error" | "waiting" | "progress" | "ended" | "change" | "input" | "select" | "abort" | "activate" | "beforeactivate" | "beforedeactivate" | "blur" | "canplay" | "canplaythrough" | "click" | "contextmenu" | "dblclick" | "deactivate" | "drag" | "dragend" | "dragenter" | "dragleave" | "dragover" | "dragstart" | "drop" | "durationchange" | "emptied" | "focus" | "invalid" | "keydown" | "keypress" | "keyup" | "load" | "loadeddata" | "loadedmetadata" | "loadstart" | "mousedown" | "mousemove" | "mouseout" | "mouseover" | "mouseup" | "mousewheel" | "MSContentZoom" | "MSGestureChange" | "MSGestureDoubleTap" | "MSGestureEnd" | "MSGestureHold" | "MSGestureStart" | "MSGestureTap" | "MSInertiaStart" | "MSManipulationStateChanged" | "MSPointerCancel" | "MSPointerDown" | "MSPointerEnter" | "MSPointerLeave" | "MSPointerMove" | "MSPointerOut" | "MSPointerOver" | "MSPointerUp" | "pause" | "play" | "playing" | "ratechange" | "reset" | "scroll" | "seeked" | "seeking" | "selectstart" | "stalled" | "submit" | "suspend" | "timeupdate" | "touchcancel" | "touchend" | "touchmove" | "touchstart" | "volumechange" | "webkitfullscreenchange" | "webkitfullscreenerror" | "pointercancel" | "pointerdown" | "pointerenter" | "pointerleave" | "pointermove" | "pointerout" | "pointerover" | "pointerup" | "wheel" | "ariarequest" | "command" | "gotpointercapture" | "lostpointercapture" | "MSGotPointerCapture" | "MSLostPointerCapture" | "beforecopy" | "beforecut" | "beforepaste" | "copy" | "cuechange" | "cut" | "mouseenter" | "mouseleave" | "paste">(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, useCapture?: boolean | undefined): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean | undefined): void;
        readonly classList: DOMTokenList;
        className: string;
        readonly clientHeight: number;
        readonly clientLeft: number;
        readonly clientTop: number;
        readonly clientWidth: number;
        id: string;
        innerHTML: string;
        msContentZoomFactor: number;
        readonly msRegionOverflow: string;
        onariarequest: (this: Element, ev: Event) => any;
        oncommand: (this: Element, ev: Event) => any;
        ongotpointercapture: (this: Element, ev: PointerEvent) => any;
        onlostpointercapture: (this: Element, ev: PointerEvent) => any;
        onmsgesturechange: (this: Element, ev: MSGestureEvent) => any;
        onmsgesturedoubletap: (this: Element, ev: MSGestureEvent) => any;
        onmsgestureend: (this: Element, ev: MSGestureEvent) => any;
        onmsgesturehold: (this: Element, ev: MSGestureEvent) => any;
        onmsgesturestart: (this: Element, ev: MSGestureEvent) => any;
        onmsgesturetap: (this: Element, ev: MSGestureEvent) => any;
        onmsgotpointercapture: (this: Element, ev: MSPointerEvent) => any;
        onmsinertiastart: (this: Element, ev: MSGestureEvent) => any;
        onmslostpointercapture: (this: Element, ev: MSPointerEvent) => any;
        onmspointercancel: (this: Element, ev: MSPointerEvent) => any;
        onmspointerdown: (this: Element, ev: MSPointerEvent) => any;
        onmspointerenter: (this: Element, ev: MSPointerEvent) => any;
        onmspointerleave: (this: Element, ev: MSPointerEvent) => any;
        onmspointermove: (this: Element, ev: MSPointerEvent) => any;
        onmspointerout: (this: Element, ev: MSPointerEvent) => any;
        onmspointerover: (this: Element, ev: MSPointerEvent) => any;
        onmspointerup: (this: Element, ev: MSPointerEvent) => any;
        ontouchcancel: (ev: TouchEvent) => any;
        ontouchend: (ev: TouchEvent) => any;
        ontouchmove: (ev: TouchEvent) => any;
        ontouchstart: (ev: TouchEvent) => any;
        onwebkitfullscreenchange: (this: Element, ev: Event) => any;
        onwebkitfullscreenerror: (this: Element, ev: Event) => any;
        outerHTML: string;
        readonly prefix: string | null;
        readonly scrollHeight: number;
        scrollLeft: number;
        scrollTop: number;
        readonly scrollWidth: number;
        readonly tagName: string;
        readonly assignedSlot: HTMLSlotElement | null;
        slot: string;
        getAttribute(name: string): string | null;
        getAttributeNode(name: string): Attr;
        getAttributeNodeNS(namespaceURI: string, localName: string): Attr;
        getAttributeNS(namespaceURI: string, localName: string): string;
        getBoundingClientRect(): ClientRect;
        getClientRects(): ClientRectList;
        getElementsByTagName<K extends "symbol" | "object" | "track" | "progress" | "a" | "applet" | "area" | "audio" | "base" | "basefont" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "col" | "colgroup" | "data" | "datalist" | "del" | "dir" | "div" | "dl" | "embed" | "fieldset" | "font" | "form" | "frame" | "frameset" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "hr" | "html" | "iframe" | "img" | "input" | "ins" | "isindex" | "label" | "legend" | "li" | "link" | "listing" | "map" | "marquee" | "menu" | "meta" | "meter" | "nextid" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "q" | "script" | "select" | "source" | "span" | "style" | "table" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "ul" | "video" | "x-ms-webview" | "xmp" | "circle" | "defs" | "desc" | "ellipse" | "filter" | "g" | "image" | "line" | "marker" | "mask" | "path" | "metadata" | "pattern" | "polygon" | "polyline" | "rect" | "svg" | "stop" | "switch" | "tspan" | "text" | "use" | "view" | "abbr" | "acronym" | "address" | "article" | "aside" | "b" | "bdo" | "big" | "center" | "cite" | "clippath" | "code" | "dd" | "dfn" | "dt" | "em" | "feblend" | "fecolormatrix" | "fecomponenttransfer" | "fecomposite" | "feconvolvematrix" | "fediffuselighting" | "fedisplacementmap" | "fedistantlight" | "feflood" | "fefunca" | "fefuncb" | "fefuncg" | "fefuncr" | "fegaussianblur" | "feimage" | "femerge" | "femergenode" | "femorphology" | "feoffset" | "fepointlight" | "fespecularlighting" | "fespotlight" | "fetile" | "feturbulence" | "figcaption" | "figure" | "footer" | "foreignobject" | "header" | "hgroup" | "i" | "kbd" | "keygen" | "lineargradient" | "mark" | "nav" | "nobr" | "noframes" | "noscript" | "plaintext" | "radialgradient" | "rt" | "ruby" | "s" | "samp" | "section" | "small" | "strike" | "strong" | "sub" | "sup" | "textpath" | "tt" | "u" | "var" | "wbr">(name: K): ElementListTagNameMap[K];
        getElementsByTagName(name: string): NodeListOf<Element>;
        getElementsByTagNameNS(namespaceURI: "http://www.w3.org/1999/xhtml", localName: string): HTMLCollectionOf<HTMLElement>;
        getElementsByTagNameNS(namespaceURI: "http://www.w3.org/2000/svg", localName: string): HTMLCollectionOf<SVGElement>;
        getElementsByTagNameNS(namespaceURI: string, localName: string): HTMLCollectionOf<Element>;
        hasAttribute(name: string): boolean;
        hasAttributeNS(namespaceURI: string, localName: string): boolean;
        msGetRegionContent(): MSRangeCollection;
        msGetUntransformedBounds(): ClientRect;
        msMatchesSelector(selectors: string): boolean;
        msReleasePointerCapture(pointerId: number): void;
        msSetPointerCapture(pointerId: number): void;
        msZoomTo(args: MsZoomToOptions): void;
        releasePointerCapture(pointerId: number): void;
        removeAttribute(qualifiedName: string): void;
        removeAttributeNode(oldAttr: Attr): Attr;
        removeAttributeNS(namespaceURI: string, localName: string): void;
        requestFullscreen(): void;
        requestPointerLock(): void;
        setAttribute(name: string, value: string): void;
        setAttributeNode(newAttr: Attr): Attr;
        setAttributeNodeNS(newAttr: Attr): Attr;
        setAttributeNS(namespaceURI: string, qualifiedName: string, value: string): void;
        setPointerCapture(pointerId: number): void;
        webkitMatchesSelector(selectors: string): boolean;
        webkitRequestFullscreen(): void;
        webkitRequestFullScreen(): void;
        getElementsByClassName(classNames: string): NodeListOf<Element>;
        matches(selector: string): boolean;
        closest(selector: string): Element | null;
        scrollIntoView(arg?: boolean | ScrollIntoViewOptions | undefined): void;
        scroll(options?: ScrollToOptions | undefined): void;
        scroll(x: number, y: number): void;
        scrollTo(options?: ScrollToOptions | undefined): void;
        scrollTo(x: number, y: number): void;
        scrollBy(options?: ScrollToOptions | undefined): void;
        scrollBy(x: number, y: number): void;
        insertAdjacentElement(position: InsertPosition, insertedElement: Element): Element | null;
        insertAdjacentHTML(where: InsertPosition, html: string): void;
        insertAdjacentText(where: InsertPosition, text: string): void;
        attachShadow(shadowRootInitDict: ShadowRootInit): ShadowRoot;
        readonly attributes: NamedNodeMap;
        readonly baseURI: string | null;
        readonly childNodes: NodeList;
        readonly firstChild: Node | null;
        readonly lastChild: Node | null;
        readonly localName: string | null;
        readonly namespaceURI: string | null;
        readonly nextSibling: Node | null;
        readonly nodeName: string;
        readonly nodeType: number;
        nodeValue: string | null;
        readonly ownerDocument: Document;
        readonly parentElement: HTMLElement | null;
        readonly parentNode: Node | null;
        readonly previousSibling: Node | null;
        textContent: string | null;
        appendChild<T extends Node>(newChild: T): T;
        cloneNode(deep?: boolean | undefined): Node;
        compareDocumentPosition(other: Node): number;
        contains(child: Node): boolean;
        hasAttributes(): boolean;
        hasChildNodes(): boolean;
        insertBefore<T extends Node>(newChild: T, refChild: Node | null): T;
        isDefaultNamespace(namespaceURI: string | null): boolean;
        isEqualNode(arg: Node): boolean;
        isSameNode(other: Node): boolean;
        lookupNamespaceURI(prefix: string | null): string | null;
        lookupPrefix(namespaceURI: string | null): string | null;
        normalize(): void;
        removeChild<T extends Node>(oldChild: T): T;
        replaceChild<T extends Node>(newChild: Node, oldChild: T): T;
        readonly ATTRIBUTE_NODE: number;
        readonly CDATA_SECTION_NODE: number;
        readonly COMMENT_NODE: number;
        readonly DOCUMENT_FRAGMENT_NODE: number;
        readonly DOCUMENT_NODE: number;
        readonly DOCUMENT_POSITION_CONTAINED_BY: number;
        readonly DOCUMENT_POSITION_CONTAINS: number;
        readonly DOCUMENT_POSITION_DISCONNECTED: number;
        readonly DOCUMENT_POSITION_FOLLOWING: number;
        readonly DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: number;
        readonly DOCUMENT_POSITION_PRECEDING: number;
        readonly DOCUMENT_TYPE_NODE: number;
        readonly ELEMENT_NODE: number;
        readonly ENTITY_NODE: number;
        readonly ENTITY_REFERENCE_NODE: number;
        readonly NOTATION_NODE: number;
        readonly PROCESSING_INSTRUCTION_NODE: number;
        readonly TEXT_NODE: number;
        dispatchEvent(evt: Event): boolean;
        removeEventListener(type: string, listener?: EventListener | EventListenerObject | undefined, options?: boolean | EventListenerOptions | undefined): void;
        onpointercancel: (this: GlobalEventHandlers, ev: PointerEvent) => any;
        onpointerdown: (this: GlobalEventHandlers, ev: PointerEvent) => any;
        onpointerenter: (this: GlobalEventHandlers, ev: PointerEvent) => any;
        onpointerleave: (this: GlobalEventHandlers, ev: PointerEvent) => any;
        onpointermove: (this: GlobalEventHandlers, ev: PointerEvent) => any;
        onpointerout: (this: GlobalEventHandlers, ev: PointerEvent) => any;
        onpointerover: (this: GlobalEventHandlers, ev: PointerEvent) => any;
        onpointerup: (this: GlobalEventHandlers, ev: PointerEvent) => any;
        onwheel: (this: GlobalEventHandlers, ev: WheelEvent) => any;
        readonly childElementCount: number;
        readonly firstElementChild: Element | null;
        readonly lastElementChild: Element | null;
        readonly nextElementSibling: Element | null;
        readonly previousElementSibling: Element | null;
        querySelector<K extends "symbol" | "object" | "track" | "progress" | "a" | "applet" | "area" | "audio" | "base" | "basefont" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "col" | "colgroup" | "data" | "datalist" | "del" | "dir" | "div" | "dl" | "embed" | "fieldset" | "font" | "form" | "frame" | "frameset" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "hr" | "html" | "iframe" | "img" | "input" | "ins" | "isindex" | "label" | "legend" | "li" | "link" | "listing" | "map" | "marquee" | "menu" | "meta" | "meter" | "nextid" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "q" | "script" | "select" | "source" | "span" | "style" | "table" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "ul" | "video" | "x-ms-webview" | "xmp" | "circle" | "defs" | "desc" | "ellipse" | "filter" | "g" | "image" | "line" | "marker" | "mask" | "path" | "metadata" | "pattern" | "polygon" | "polyline" | "rect" | "svg" | "stop" | "switch" | "tspan" | "text" | "use" | "view" | "abbr" | "acronym" | "address" | "article" | "aside" | "b" | "bdo" | "big" | "center" | "cite" | "clippath" | "code" | "dd" | "dfn" | "dt" | "em" | "feblend" | "fecolormatrix" | "fecomponenttransfer" | "fecomposite" | "feconvolvematrix" | "fediffuselighting" | "fedisplacementmap" | "fedistantlight" | "feflood" | "fefunca" | "fefuncb" | "fefuncg" | "fefuncr" | "fegaussianblur" | "feimage" | "femerge" | "femergenode" | "femorphology" | "feoffset" | "fepointlight" | "fespecularlighting" | "fespotlight" | "fetile" | "feturbulence" | "figcaption" | "figure" | "footer" | "foreignobject" | "header" | "hgroup" | "i" | "kbd" | "keygen" | "lineargradient" | "mark" | "nav" | "nobr" | "noframes" | "noscript" | "plaintext" | "radialgradient" | "rt" | "ruby" | "s" | "samp" | "section" | "small" | "strike" | "strong" | "sub" | "sup" | "textpath" | "tt" | "u" | "var" | "wbr">(selectors: K): ElementTagNameMap[K] | null;
        querySelector(selectors: string): Element | null;
        querySelectorAll<K extends "symbol" | "object" | "track" | "progress" | "a" | "applet" | "area" | "audio" | "base" | "basefont" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "col" | "colgroup" | "data" | "datalist" | "del" | "dir" | "div" | "dl" | "embed" | "fieldset" | "font" | "form" | "frame" | "frameset" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "hr" | "html" | "iframe" | "img" | "input" | "ins" | "isindex" | "label" | "legend" | "li" | "link" | "listing" | "map" | "marquee" | "menu" | "meta" | "meter" | "nextid" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "q" | "script" | "select" | "source" | "span" | "style" | "table" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "ul" | "video" | "x-ms-webview" | "xmp" | "circle" | "defs" | "desc" | "ellipse" | "filter" | "g" | "image" | "line" | "marker" | "mask" | "path" | "metadata" | "pattern" | "polygon" | "polyline" | "rect" | "svg" | "stop" | "switch" | "tspan" | "text" | "use" | "view" | "abbr" | "acronym" | "address" | "article" | "aside" | "b" | "bdo" | "big" | "center" | "cite" | "clippath" | "code" | "dd" | "dfn" | "dt" | "em" | "feblend" | "fecolormatrix" | "fecomponenttransfer" | "fecomposite" | "feconvolvematrix" | "fediffuselighting" | "fedisplacementmap" | "fedistantlight" | "feflood" | "fefunca" | "fefuncb" | "fefuncg" | "fefuncr" | "fegaussianblur" | "feimage" | "femerge" | "femergenode" | "femorphology" | "feoffset" | "fepointlight" | "fespecularlighting" | "fespotlight" | "fetile" | "feturbulence" | "figcaption" | "figure" | "footer" | "foreignobject" | "header" | "hgroup" | "i" | "kbd" | "keygen" | "lineargradient" | "mark" | "nav" | "nobr" | "noframes" | "noscript" | "plaintext" | "radialgradient" | "rt" | "ruby" | "s" | "samp" | "section" | "small" | "strike" | "strong" | "sub" | "sup" | "textpath" | "tt" | "u" | "var" | "wbr">(selectors: K): ElementListTagNameMap[K];
        querySelectorAll(selectors: string): NodeListOf<Element>;
        remove(): void;
    };
    properties: properties;
    observedAttributes(): string[];
    accessKey: string;
    readonly children: HTMLCollection;
    contentEditable: string;
    readonly dataset: DOMStringMap;
    dir: string;
    draggable: boolean;
    hidden: boolean;
    hideFocus: boolean;
    innerText: string;
    readonly isContentEditable: boolean;
    lang: string;
    readonly offsetHeight: number;
    readonly offsetLeft: number;
    readonly offsetParent: Element;
    readonly offsetTop: number;
    readonly offsetWidth: number;
    onabort: (this: HTMLElement, ev: UIEvent) => any;
    onactivate: (this: HTMLElement, ev: UIEvent) => any;
    onbeforeactivate: (this: HTMLElement, ev: UIEvent) => any;
    onbeforecopy: (this: HTMLElement, ev: ClipboardEvent) => any;
    onbeforecut: (this: HTMLElement, ev: ClipboardEvent) => any;
    onbeforedeactivate: (this: HTMLElement, ev: UIEvent) => any;
    onbeforepaste: (this: HTMLElement, ev: ClipboardEvent) => any;
    onblur: (this: HTMLElement, ev: FocusEvent) => any;
    oncanplay: (this: HTMLElement, ev: Event) => any;
    oncanplaythrough: (this: HTMLElement, ev: Event) => any;
    onchange: (this: HTMLElement, ev: Event) => any;
    onclick: (this: HTMLElement, ev: MouseEvent) => any;
    oncontextmenu: (this: HTMLElement, ev: PointerEvent) => any;
    oncopy: (this: HTMLElement, ev: ClipboardEvent) => any;
    oncuechange: (this: HTMLElement, ev: Event) => any;
    oncut: (this: HTMLElement, ev: ClipboardEvent) => any;
    ondblclick: (this: HTMLElement, ev: MouseEvent) => any;
    ondeactivate: (this: HTMLElement, ev: UIEvent) => any;
    ondrag: (this: HTMLElement, ev: DragEvent) => any;
    ondragend: (this: HTMLElement, ev: DragEvent) => any;
    ondragenter: (this: HTMLElement, ev: DragEvent) => any;
    ondragleave: (this: HTMLElement, ev: DragEvent) => any;
    ondragover: (this: HTMLElement, ev: DragEvent) => any;
    ondragstart: (this: HTMLElement, ev: DragEvent) => any;
    ondrop: (this: HTMLElement, ev: DragEvent) => any;
    ondurationchange: (this: HTMLElement, ev: Event) => any;
    onemptied: (this: HTMLElement, ev: Event) => any;
    onended: (this: HTMLElement, ev: MediaStreamErrorEvent) => any;
    onerror: (this: HTMLElement, ev: ErrorEvent) => any;
    onfocus: (this: HTMLElement, ev: FocusEvent) => any;
    oninput: (this: HTMLElement, ev: Event) => any;
    oninvalid: (this: HTMLElement, ev: Event) => any;
    onkeydown: (this: HTMLElement, ev: KeyboardEvent) => any;
    onkeypress: (this: HTMLElement, ev: KeyboardEvent) => any;
    onkeyup: (this: HTMLElement, ev: KeyboardEvent) => any;
    onload: (this: HTMLElement, ev: Event) => any;
    onloadeddata: (this: HTMLElement, ev: Event) => any;
    onloadedmetadata: (this: HTMLElement, ev: Event) => any;
    onloadstart: (this: HTMLElement, ev: Event) => any;
    onmousedown: (this: HTMLElement, ev: MouseEvent) => any;
    onmouseenter: (this: HTMLElement, ev: MouseEvent) => any;
    onmouseleave: (this: HTMLElement, ev: MouseEvent) => any;
    onmousemove: (this: HTMLElement, ev: MouseEvent) => any;
    onmouseout: (this: HTMLElement, ev: MouseEvent) => any;
    onmouseover: (this: HTMLElement, ev: MouseEvent) => any;
    onmouseup: (this: HTMLElement, ev: MouseEvent) => any;
    onmousewheel: (this: HTMLElement, ev: WheelEvent) => any;
    onmscontentzoom: (this: HTMLElement, ev: UIEvent) => any;
    onmsmanipulationstatechanged: (this: HTMLElement, ev: MSManipulationEvent) => any;
    onpaste: (this: HTMLElement, ev: ClipboardEvent) => any;
    onpause: (this: HTMLElement, ev: Event) => any;
    onplay: (this: HTMLElement, ev: Event) => any;
    onplaying: (this: HTMLElement, ev: Event) => any;
    onprogress: (this: HTMLElement, ev: ProgressEvent) => any;
    onratechange: (this: HTMLElement, ev: Event) => any;
    onreset: (this: HTMLElement, ev: Event) => any;
    onscroll: (this: HTMLElement, ev: UIEvent) => any;
    onseeked: (this: HTMLElement, ev: Event) => any;
    onseeking: (this: HTMLElement, ev: Event) => any;
    onselect: (this: HTMLElement, ev: UIEvent) => any;
    onselectstart: (this: HTMLElement, ev: Event) => any;
    onstalled: (this: HTMLElement, ev: Event) => any;
    onsubmit: (this: HTMLElement, ev: Event) => any;
    onsuspend: (this: HTMLElement, ev: Event) => any;
    ontimeupdate: (this: HTMLElement, ev: Event) => any;
    onvolumechange: (this: HTMLElement, ev: Event) => any;
    onwaiting: (this: HTMLElement, ev: Event) => any;
    outerText: string;
    spellcheck: boolean;
    readonly style: CSSStyleDeclaration;
    tabIndex: number;
    title: string;
    blur(): void;
    click(): void;
    dragDrop(): boolean;
    focus(): void;
    msGetInputContext(): MSInputMethodContext;
    addEventListener<K extends "error" | "waiting" | "progress" | "ended" | "change" | "input" | "select" | "abort" | "activate" | "beforeactivate" | "beforedeactivate" | "blur" | "canplay" | "canplaythrough" | "click" | "contextmenu" | "dblclick" | "deactivate" | "drag" | "dragend" | "dragenter" | "dragleave" | "dragover" | "dragstart" | "drop" | "durationchange" | "emptied" | "focus" | "invalid" | "keydown" | "keypress" | "keyup" | "load" | "loadeddata" | "loadedmetadata" | "loadstart" | "mousedown" | "mousemove" | "mouseout" | "mouseover" | "mouseup" | "mousewheel" | "MSContentZoom" | "MSGestureChange" | "MSGestureDoubleTap" | "MSGestureEnd" | "MSGestureHold" | "MSGestureStart" | "MSGestureTap" | "MSInertiaStart" | "MSManipulationStateChanged" | "MSPointerCancel" | "MSPointerDown" | "MSPointerEnter" | "MSPointerLeave" | "MSPointerMove" | "MSPointerOut" | "MSPointerOver" | "MSPointerUp" | "pause" | "play" | "playing" | "ratechange" | "reset" | "scroll" | "seeked" | "seeking" | "selectstart" | "stalled" | "submit" | "suspend" | "timeupdate" | "touchcancel" | "touchend" | "touchmove" | "touchstart" | "volumechange" | "webkitfullscreenchange" | "webkitfullscreenerror" | "pointercancel" | "pointerdown" | "pointerenter" | "pointerleave" | "pointermove" | "pointerout" | "pointerover" | "pointerup" | "wheel" | "ariarequest" | "command" | "gotpointercapture" | "lostpointercapture" | "MSGotPointerCapture" | "MSLostPointerCapture" | "beforecopy" | "beforecut" | "beforepaste" | "copy" | "cuechange" | "cut" | "mouseenter" | "mouseleave" | "paste">(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, useCapture?: boolean | undefined): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean | undefined): void;
    readonly classList: DOMTokenList;
    className: string;
    readonly clientHeight: number;
    readonly clientLeft: number;
    readonly clientTop: number;
    readonly clientWidth: number;
    id: string;
    innerHTML: string;
    msContentZoomFactor: number;
    readonly msRegionOverflow: string;
    onariarequest: (this: Element, ev: Event) => any;
    oncommand: (this: Element, ev: Event) => any;
    ongotpointercapture: (this: Element, ev: PointerEvent) => any;
    onlostpointercapture: (this: Element, ev: PointerEvent) => any;
    onmsgesturechange: (this: Element, ev: MSGestureEvent) => any;
    onmsgesturedoubletap: (this: Element, ev: MSGestureEvent) => any;
    onmsgestureend: (this: Element, ev: MSGestureEvent) => any;
    onmsgesturehold: (this: Element, ev: MSGestureEvent) => any;
    onmsgesturestart: (this: Element, ev: MSGestureEvent) => any;
    onmsgesturetap: (this: Element, ev: MSGestureEvent) => any;
    onmsgotpointercapture: (this: Element, ev: MSPointerEvent) => any;
    onmsinertiastart: (this: Element, ev: MSGestureEvent) => any;
    onmslostpointercapture: (this: Element, ev: MSPointerEvent) => any;
    onmspointercancel: (this: Element, ev: MSPointerEvent) => any;
    onmspointerdown: (this: Element, ev: MSPointerEvent) => any;
    onmspointerenter: (this: Element, ev: MSPointerEvent) => any;
    onmspointerleave: (this: Element, ev: MSPointerEvent) => any;
    onmspointermove: (this: Element, ev: MSPointerEvent) => any;
    onmspointerout: (this: Element, ev: MSPointerEvent) => any;
    onmspointerover: (this: Element, ev: MSPointerEvent) => any;
    onmspointerup: (this: Element, ev: MSPointerEvent) => any;
    ontouchcancel: (ev: TouchEvent) => any;
    ontouchend: (ev: TouchEvent) => any;
    ontouchmove: (ev: TouchEvent) => any;
    ontouchstart: (ev: TouchEvent) => any;
    onwebkitfullscreenchange: (this: Element, ev: Event) => any;
    onwebkitfullscreenerror: (this: Element, ev: Event) => any;
    outerHTML: string;
    readonly prefix: string | null;
    readonly scrollHeight: number;
    scrollLeft: number;
    scrollTop: number;
    readonly scrollWidth: number;
    readonly tagName: string;
    readonly assignedSlot: HTMLSlotElement | null;
    slot: string;
    readonly shadowRoot: ShadowRoot | null;
    getAttribute(name: string): string | null;
    getAttributeNode(name: string): Attr;
    getAttributeNodeNS(namespaceURI: string, localName: string): Attr;
    getAttributeNS(namespaceURI: string, localName: string): string;
    getBoundingClientRect(): ClientRect;
    getClientRects(): ClientRectList;
    getElementsByTagName<K extends "symbol" | "object" | "track" | "progress" | "a" | "applet" | "area" | "audio" | "base" | "basefont" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "col" | "colgroup" | "data" | "datalist" | "del" | "dir" | "div" | "dl" | "embed" | "fieldset" | "font" | "form" | "frame" | "frameset" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "hr" | "html" | "iframe" | "img" | "input" | "ins" | "isindex" | "label" | "legend" | "li" | "link" | "listing" | "map" | "marquee" | "menu" | "meta" | "meter" | "nextid" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "q" | "script" | "select" | "source" | "span" | "style" | "table" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "ul" | "video" | "x-ms-webview" | "xmp" | "circle" | "defs" | "desc" | "ellipse" | "filter" | "g" | "image" | "line" | "marker" | "mask" | "path" | "metadata" | "pattern" | "polygon" | "polyline" | "rect" | "svg" | "stop" | "switch" | "tspan" | "text" | "use" | "view" | "abbr" | "acronym" | "address" | "article" | "aside" | "b" | "bdo" | "big" | "center" | "cite" | "clippath" | "code" | "dd" | "dfn" | "dt" | "em" | "feblend" | "fecolormatrix" | "fecomponenttransfer" | "fecomposite" | "feconvolvematrix" | "fediffuselighting" | "fedisplacementmap" | "fedistantlight" | "feflood" | "fefunca" | "fefuncb" | "fefuncg" | "fefuncr" | "fegaussianblur" | "feimage" | "femerge" | "femergenode" | "femorphology" | "feoffset" | "fepointlight" | "fespecularlighting" | "fespotlight" | "fetile" | "feturbulence" | "figcaption" | "figure" | "footer" | "foreignobject" | "header" | "hgroup" | "i" | "kbd" | "keygen" | "lineargradient" | "mark" | "nav" | "nobr" | "noframes" | "noscript" | "plaintext" | "radialgradient" | "rt" | "ruby" | "s" | "samp" | "section" | "small" | "strike" | "strong" | "sub" | "sup" | "textpath" | "tt" | "u" | "var" | "wbr">(name: K): ElementListTagNameMap[K];
    getElementsByTagName(name: string): NodeListOf<Element>;
    getElementsByTagNameNS(namespaceURI: "http://www.w3.org/1999/xhtml", localName: string): HTMLCollectionOf<HTMLElement>;
    getElementsByTagNameNS(namespaceURI: "http://www.w3.org/2000/svg", localName: string): HTMLCollectionOf<SVGElement>;
    getElementsByTagNameNS(namespaceURI: string, localName: string): HTMLCollectionOf<Element>;
    hasAttribute(name: string): boolean;
    hasAttributeNS(namespaceURI: string, localName: string): boolean;
    msGetRegionContent(): MSRangeCollection;
    msGetUntransformedBounds(): ClientRect;
    msMatchesSelector(selectors: string): boolean;
    msReleasePointerCapture(pointerId: number): void;
    msSetPointerCapture(pointerId: number): void;
    msZoomTo(args: MsZoomToOptions): void;
    releasePointerCapture(pointerId: number): void;
    removeAttribute(qualifiedName: string): void;
    removeAttributeNode(oldAttr: Attr): Attr;
    removeAttributeNS(namespaceURI: string, localName: string): void;
    requestFullscreen(): void;
    requestPointerLock(): void;
    setAttribute(name: string, value: string): void;
    setAttributeNode(newAttr: Attr): Attr;
    setAttributeNodeNS(newAttr: Attr): Attr;
    setAttributeNS(namespaceURI: string, qualifiedName: string, value: string): void;
    setPointerCapture(pointerId: number): void;
    webkitMatchesSelector(selectors: string): boolean;
    webkitRequestFullscreen(): void;
    webkitRequestFullScreen(): void;
    getElementsByClassName(classNames: string): NodeListOf<Element>;
    matches(selector: string): boolean;
    closest(selector: string): Element | null;
    scrollIntoView(arg?: boolean | ScrollIntoViewOptions | undefined): void;
    scroll(options?: ScrollToOptions | undefined): void;
    scroll(x: number, y: number): void;
    scrollTo(options?: ScrollToOptions | undefined): void;
    scrollTo(x: number, y: number): void;
    scrollBy(options?: ScrollToOptions | undefined): void;
    scrollBy(x: number, y: number): void;
    insertAdjacentElement(position: InsertPosition, insertedElement: Element): Element | null;
    insertAdjacentHTML(where: InsertPosition, html: string): void;
    insertAdjacentText(where: InsertPosition, text: string): void;
    attachShadow(shadowRootInitDict: ShadowRootInit): ShadowRoot;
    readonly attributes: NamedNodeMap;
    readonly baseURI: string | null;
    readonly childNodes: NodeList;
    readonly firstChild: Node | null;
    readonly lastChild: Node | null;
    readonly localName: string | null;
    readonly namespaceURI: string | null;
    readonly nextSibling: Node | null;
    readonly nodeName: string;
    readonly nodeType: number;
    nodeValue: string | null;
    readonly ownerDocument: Document;
    readonly parentElement: HTMLElement | null;
    readonly parentNode: Node | null;
    readonly previousSibling: Node | null;
    textContent: string | null;
    appendChild<T extends Node>(newChild: T): T;
    cloneNode(deep?: boolean | undefined): Node;
    compareDocumentPosition(other: Node): number;
    contains(child: Node): boolean;
    hasAttributes(): boolean;
    hasChildNodes(): boolean;
    insertBefore<T extends Node>(newChild: T, refChild: Node | null): T;
    isDefaultNamespace(namespaceURI: string | null): boolean;
    isEqualNode(arg: Node): boolean;
    isSameNode(other: Node): boolean;
    lookupNamespaceURI(prefix: string | null): string | null;
    lookupPrefix(namespaceURI: string | null): string | null;
    normalize(): void;
    removeChild<T extends Node>(oldChild: T): T;
    replaceChild<T extends Node>(newChild: Node, oldChild: T): T;
    readonly ATTRIBUTE_NODE: number;
    readonly CDATA_SECTION_NODE: number;
    readonly COMMENT_NODE: number;
    readonly DOCUMENT_FRAGMENT_NODE: number;
    readonly DOCUMENT_NODE: number;
    readonly DOCUMENT_POSITION_CONTAINED_BY: number;
    readonly DOCUMENT_POSITION_CONTAINS: number;
    readonly DOCUMENT_POSITION_DISCONNECTED: number;
    readonly DOCUMENT_POSITION_FOLLOWING: number;
    readonly DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: number;
    readonly DOCUMENT_POSITION_PRECEDING: number;
    readonly DOCUMENT_TYPE_NODE: number;
    readonly ELEMENT_NODE: number;
    readonly ENTITY_NODE: number;
    readonly ENTITY_REFERENCE_NODE: number;
    readonly NOTATION_NODE: number;
    readonly PROCESSING_INSTRUCTION_NODE: number;
    readonly TEXT_NODE: number;
    dispatchEvent(evt: Event): boolean;
    removeEventListener(type: string, listener?: EventListener | EventListenerObject | undefined, options?: boolean | EventListenerOptions | undefined): void;
    onpointercancel: (this: GlobalEventHandlers, ev: PointerEvent) => any;
    onpointerdown: (this: GlobalEventHandlers, ev: PointerEvent) => any;
    onpointerenter: (this: GlobalEventHandlers, ev: PointerEvent) => any;
    onpointerleave: (this: GlobalEventHandlers, ev: PointerEvent) => any;
    onpointermove: (this: GlobalEventHandlers, ev: PointerEvent) => any;
    onpointerout: (this: GlobalEventHandlers, ev: PointerEvent) => any;
    onpointerover: (this: GlobalEventHandlers, ev: PointerEvent) => any;
    onpointerup: (this: GlobalEventHandlers, ev: PointerEvent) => any;
    onwheel: (this: GlobalEventHandlers, ev: WheelEvent) => any;
    readonly childElementCount: number;
    readonly firstElementChild: Element | null;
    readonly lastElementChild: Element | null;
    readonly nextElementSibling: Element | null;
    readonly previousElementSibling: Element | null;
    querySelector<K extends "symbol" | "object" | "track" | "progress" | "a" | "applet" | "area" | "audio" | "base" | "basefont" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "col" | "colgroup" | "data" | "datalist" | "del" | "dir" | "div" | "dl" | "embed" | "fieldset" | "font" | "form" | "frame" | "frameset" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "hr" | "html" | "iframe" | "img" | "input" | "ins" | "isindex" | "label" | "legend" | "li" | "link" | "listing" | "map" | "marquee" | "menu" | "meta" | "meter" | "nextid" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "q" | "script" | "select" | "source" | "span" | "style" | "table" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "ul" | "video" | "x-ms-webview" | "xmp" | "circle" | "defs" | "desc" | "ellipse" | "filter" | "g" | "image" | "line" | "marker" | "mask" | "path" | "metadata" | "pattern" | "polygon" | "polyline" | "rect" | "svg" | "stop" | "switch" | "tspan" | "text" | "use" | "view" | "abbr" | "acronym" | "address" | "article" | "aside" | "b" | "bdo" | "big" | "center" | "cite" | "clippath" | "code" | "dd" | "dfn" | "dt" | "em" | "feblend" | "fecolormatrix" | "fecomponenttransfer" | "fecomposite" | "feconvolvematrix" | "fediffuselighting" | "fedisplacementmap" | "fedistantlight" | "feflood" | "fefunca" | "fefuncb" | "fefuncg" | "fefuncr" | "fegaussianblur" | "feimage" | "femerge" | "femergenode" | "femorphology" | "feoffset" | "fepointlight" | "fespecularlighting" | "fespotlight" | "fetile" | "feturbulence" | "figcaption" | "figure" | "footer" | "foreignobject" | "header" | "hgroup" | "i" | "kbd" | "keygen" | "lineargradient" | "mark" | "nav" | "nobr" | "noframes" | "noscript" | "plaintext" | "radialgradient" | "rt" | "ruby" | "s" | "samp" | "section" | "small" | "strike" | "strong" | "sub" | "sup" | "textpath" | "tt" | "u" | "var" | "wbr">(selectors: K): ElementTagNameMap[K] | null;
    querySelector(selectors: string): Element | null;
    querySelectorAll<K extends "symbol" | "object" | "track" | "progress" | "a" | "applet" | "area" | "audio" | "base" | "basefont" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "col" | "colgroup" | "data" | "datalist" | "del" | "dir" | "div" | "dl" | "embed" | "fieldset" | "font" | "form" | "frame" | "frameset" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "hr" | "html" | "iframe" | "img" | "input" | "ins" | "isindex" | "label" | "legend" | "li" | "link" | "listing" | "map" | "marquee" | "menu" | "meta" | "meter" | "nextid" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "q" | "script" | "select" | "source" | "span" | "style" | "table" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "ul" | "video" | "x-ms-webview" | "xmp" | "circle" | "defs" | "desc" | "ellipse" | "filter" | "g" | "image" | "line" | "marker" | "mask" | "path" | "metadata" | "pattern" | "polygon" | "polyline" | "rect" | "svg" | "stop" | "switch" | "tspan" | "text" | "use" | "view" | "abbr" | "acronym" | "address" | "article" | "aside" | "b" | "bdo" | "big" | "center" | "cite" | "clippath" | "code" | "dd" | "dfn" | "dt" | "em" | "feblend" | "fecolormatrix" | "fecomponenttransfer" | "fecomposite" | "feconvolvematrix" | "fediffuselighting" | "fedisplacementmap" | "fedistantlight" | "feflood" | "fefunca" | "fefuncb" | "fefuncg" | "fefuncr" | "fegaussianblur" | "feimage" | "femerge" | "femergenode" | "femorphology" | "feoffset" | "fepointlight" | "fespecularlighting" | "fespotlight" | "fetile" | "feturbulence" | "figcaption" | "figure" | "footer" | "foreignobject" | "header" | "hgroup" | "i" | "kbd" | "keygen" | "lineargradient" | "mark" | "nav" | "nobr" | "noframes" | "noscript" | "plaintext" | "radialgradient" | "rt" | "ruby" | "s" | "samp" | "section" | "small" | "strike" | "strong" | "sub" | "sup" | "textpath" | "tt" | "u" | "var" | "wbr">(selectors: K): ElementListTagNameMap[K];
    querySelectorAll(selectors: string): NodeListOf<Element>;
    remove(): void;
};
